cmake_minimum_required(VERSION 3.22.1)
project(camera_quality_ai)
add_library(camera_quality_ai SHARED rknn_feature_extractor.cpp)
target_include_directories(camera_quality_ai PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/include)
add_library(rknnrt SHARED IMPORTED)
set_target_properties(rknnrt PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/../jniLibs/${ANDROID_ABI}/librknnrt.so)
find_library(log-lib log)
find_library(android-lib android)
target_link_libraries(camera_quality_ai rknnrt ${log-lib} ${android-lib})
